# MAA task configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: maa-config
  namespace: default
data:
  maa-config.json: |
    {
      "adb": {
        "adb_path": "adb",
        "address": "127.0.0.1:5555",
        "config": {}
      },
      "tasks": [
        {
          "type": "StartUp"
        },
        {
          "type": "Infrast"
        },
        {
          "type": "Fight",
          "stage": "1-7"
        }
      ]
    }
