# Redroid persistent storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redroid-userdata-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi # Stores Arknights game data, updates, and account state
