# Redroid 独立持久化存储
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redroid-userdata-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi # 存放明日方舟本体、更新数据及账号状态
